/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WashRouteImport } from './routes/wash'
import { Route as UpdateRequestsRouteImport } from './routes/update-requests'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TabletRouteImport } from './routes/tablet'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as StylesRouteImport } from './routes/styles'
import { Route as SkuMappingRouteImport } from './routes/sku-mapping'
import { Route as SizeRangesRouteImport } from './routes/size-ranges'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopFloorRouteImport } from './routes/shop-floor'
import { Route as SewingRouteImport } from './routes/sewing'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QcRouteImport } from './routes/qc'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as MachinesRouteImport } from './routes/machines'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CuttingRouteImport } from './routes/cutting'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as BomsRouteImport } from './routes/boms'
import { Route as ApplyIntakeRouteImport } from './routes/apply-intake'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyIndexRouteImport } from './routes/apply.index'
import { Route as SubmissionsSubmissionIdRouteImport } from './routes/submissions.$submissionId'
import { Route as StylesStyleIdRouteImport } from './routes/styles.$styleId'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsBrandingRouteImport } from './routes/settings.branding'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ApplyUpdateRouteImport } from './routes/apply.update'
import { Route as ApplyThankYouRouteImport } from './routes/apply.thank-you'
import { Route as ApplyNewRouteImport } from './routes/apply.new'
import { Route as SubmissionsSubmissionIdCutSheetRouteImport } from './routes/submissions.$submissionId.cut-sheet'
import { Route as OrdersReviewSubmissionIdRouteImport } from './routes/orders.review.$submissionId'
import { Route as ApplyStatusReferenceCodeRouteImport } from './routes/apply.status.$referenceCode'

const WashRoute = WashRouteImport.update({
  id: '/wash',
  path: '/wash',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdateRequestsRoute = UpdateRequestsRouteImport.update({
  id: '/update-requests',
  path: '/update-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TabletRoute = TabletRouteImport.update({
  id: '/tablet',
  path: '/tablet',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesRoute = StylesRouteImport.update({
  id: '/styles',
  path: '/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const SkuMappingRoute = SkuMappingRouteImport.update({
  id: '/sku-mapping',
  path: '/sku-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeRangesRoute = SizeRangesRouteImport.update({
  id: '/size-ranges',
  path: '/size-ranges',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopFloorRoute = ShopFloorRouteImport.update({
  id: '/shop-floor',
  path: '/shop-floor',
  getParentRoute: () => rootRouteImport,
} as any)
const SewingRoute = SewingRouteImport.update({
  id: '/sewing',
  path: '/sewing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QcRoute = QcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesRoute = MachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CuttingRoute = CuttingRouteImport.update({
  id: '/cutting',
  path: '/cutting',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const BomsRoute = BomsRouteImport.update({
  id: '/boms',
  path: '/boms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIntakeRoute = ApplyIntakeRouteImport.update({
  id: '/apply-intake',
  path: '/apply-intake',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/apply/',
  path: '/apply/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsSubmissionIdRoute = SubmissionsSubmissionIdRouteImport.update({
  id: '/$submissionId',
  path: '/$submissionId',
  getParentRoute: () => SubmissionsRoute,
} as any)
const StylesStyleIdRoute = StylesStyleIdRouteImport.update({
  id: '/$styleId',
  path: '/$styleId',
  getParentRoute: () => StylesRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBrandingRoute = SettingsBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => SettingsRoute,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const ApplyUpdateRoute = ApplyUpdateRouteImport.update({
  id: '/apply/update',
  path: '/apply/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyThankYouRoute = ApplyThankYouRouteImport.update({
  id: '/apply/thank-you',
  path: '/apply/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyNewRoute = ApplyNewRouteImport.update({
  id: '/apply/new',
  path: '/apply/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsSubmissionIdCutSheetRoute =
  SubmissionsSubmissionIdCutSheetRouteImport.update({
    id: '/cut-sheet',
    path: '/cut-sheet',
    getParentRoute: () => SubmissionsSubmissionIdRoute,
  } as any)
const OrdersReviewSubmissionIdRoute =
  OrdersReviewSubmissionIdRouteImport.update({
    id: '/review/$submissionId',
    path: '/review/$submissionId',
    getParentRoute: () => OrdersRoute,
  } as any)
const ApplyStatusReferenceCodeRoute =
  ApplyStatusReferenceCodeRouteImport.update({
    id: '/apply/status/$referenceCode',
    path: '/apply/status/$referenceCode',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/apply-intake': typeof ApplyIntakeRoute
  '/boms': typeof BomsRoute
  '/coming-soon': typeof ComingSoonRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/cutting': typeof CuttingRoute
  '/dashboard': typeof DashboardRoute
  '/dispatch': typeof DispatchRoute
  '/finance': typeof FinanceRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/machines': typeof MachinesRoute
  '/materials': typeof MaterialsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/qc': typeof QcRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sewing': typeof SewingRoute
  '/shop-floor': typeof ShopFloorRoute
  '/signup': typeof SignupRoute
  '/size-ranges': typeof SizeRangesRoute
  '/sku-mapping': typeof SkuMappingRoute
  '/styles': typeof StylesRouteWithChildren
  '/submissions': typeof SubmissionsRouteWithChildren
  '/sustainability': typeof SustainabilityRoute
  '/tablet': typeof TabletRoute
  '/terms': typeof TermsRoute
  '/update-requests': typeof UpdateRequestsRoute
  '/wash': typeof WashRoute
  '/apply/new': typeof ApplyNewRoute
  '/apply/thank-you': typeof ApplyThankYouRoute
  '/apply/update': typeof ApplyUpdateRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/settings/branding': typeof SettingsBrandingRoute
  '/settings/users': typeof SettingsUsersRoute
  '/styles/$styleId': typeof StylesStyleIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRouteWithChildren
  '/apply/': typeof ApplyIndexRoute
  '/apply/status/$referenceCode': typeof ApplyStatusReferenceCodeRoute
  '/orders/review/$submissionId': typeof OrdersReviewSubmissionIdRoute
  '/submissions/$submissionId/cut-sheet': typeof SubmissionsSubmissionIdCutSheetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/apply-intake': typeof ApplyIntakeRoute
  '/boms': typeof BomsRoute
  '/coming-soon': typeof ComingSoonRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/cutting': typeof CuttingRoute
  '/dashboard': typeof DashboardRoute
  '/dispatch': typeof DispatchRoute
  '/finance': typeof FinanceRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/machines': typeof MachinesRoute
  '/materials': typeof MaterialsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/qc': typeof QcRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sewing': typeof SewingRoute
  '/shop-floor': typeof ShopFloorRoute
  '/signup': typeof SignupRoute
  '/size-ranges': typeof SizeRangesRoute
  '/sku-mapping': typeof SkuMappingRoute
  '/styles': typeof StylesRouteWithChildren
  '/submissions': typeof SubmissionsRouteWithChildren
  '/sustainability': typeof SustainabilityRoute
  '/tablet': typeof TabletRoute
  '/terms': typeof TermsRoute
  '/update-requests': typeof UpdateRequestsRoute
  '/wash': typeof WashRoute
  '/apply/new': typeof ApplyNewRoute
  '/apply/thank-you': typeof ApplyThankYouRoute
  '/apply/update': typeof ApplyUpdateRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/settings/branding': typeof SettingsBrandingRoute
  '/settings/users': typeof SettingsUsersRoute
  '/styles/$styleId': typeof StylesStyleIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRouteWithChildren
  '/apply': typeof ApplyIndexRoute
  '/apply/status/$referenceCode': typeof ApplyStatusReferenceCodeRoute
  '/orders/review/$submissionId': typeof OrdersReviewSubmissionIdRoute
  '/submissions/$submissionId/cut-sheet': typeof SubmissionsSubmissionIdCutSheetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/apply-intake': typeof ApplyIntakeRoute
  '/boms': typeof BomsRoute
  '/coming-soon': typeof ComingSoonRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/cutting': typeof CuttingRoute
  '/dashboard': typeof DashboardRoute
  '/dispatch': typeof DispatchRoute
  '/finance': typeof FinanceRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/machines': typeof MachinesRoute
  '/materials': typeof MaterialsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/qc': typeof QcRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sewing': typeof SewingRoute
  '/shop-floor': typeof ShopFloorRoute
  '/signup': typeof SignupRoute
  '/size-ranges': typeof SizeRangesRoute
  '/sku-mapping': typeof SkuMappingRoute
  '/styles': typeof StylesRouteWithChildren
  '/submissions': typeof SubmissionsRouteWithChildren
  '/sustainability': typeof SustainabilityRoute
  '/tablet': typeof TabletRoute
  '/terms': typeof TermsRoute
  '/update-requests': typeof UpdateRequestsRoute
  '/wash': typeof WashRoute
  '/apply/new': typeof ApplyNewRoute
  '/apply/thank-you': typeof ApplyThankYouRoute
  '/apply/update': typeof ApplyUpdateRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/settings/branding': typeof SettingsBrandingRoute
  '/settings/users': typeof SettingsUsersRoute
  '/styles/$styleId': typeof StylesStyleIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRouteWithChildren
  '/apply/': typeof ApplyIndexRoute
  '/apply/status/$referenceCode': typeof ApplyStatusReferenceCodeRoute
  '/orders/review/$submissionId': typeof OrdersReviewSubmissionIdRoute
  '/submissions/$submissionId/cut-sheet': typeof SubmissionsSubmissionIdCutSheetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/apply-intake'
    | '/boms'
    | '/coming-soon'
    | '/compliance'
    | '/contact'
    | '/cutting'
    | '/dashboard'
    | '/dispatch'
    | '/finance'
    | '/inventory'
    | '/login'
    | '/machines'
    | '/materials'
    | '/orders'
    | '/privacy'
    | '/process'
    | '/qc'
    | '/reports'
    | '/settings'
    | '/sewing'
    | '/shop-floor'
    | '/signup'
    | '/size-ranges'
    | '/sku-mapping'
    | '/styles'
    | '/submissions'
    | '/sustainability'
    | '/tablet'
    | '/terms'
    | '/update-requests'
    | '/wash'
    | '/apply/new'
    | '/apply/thank-you'
    | '/apply/update'
    | '/orders/$orderId'
    | '/settings/branding'
    | '/settings/users'
    | '/styles/$styleId'
    | '/submissions/$submissionId'
    | '/apply/'
    | '/apply/status/$referenceCode'
    | '/orders/review/$submissionId'
    | '/submissions/$submissionId/cut-sheet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/apply-intake'
    | '/boms'
    | '/coming-soon'
    | '/compliance'
    | '/contact'
    | '/cutting'
    | '/dashboard'
    | '/dispatch'
    | '/finance'
    | '/inventory'
    | '/login'
    | '/machines'
    | '/materials'
    | '/orders'
    | '/privacy'
    | '/process'
    | '/qc'
    | '/reports'
    | '/settings'
    | '/sewing'
    | '/shop-floor'
    | '/signup'
    | '/size-ranges'
    | '/sku-mapping'
    | '/styles'
    | '/submissions'
    | '/sustainability'
    | '/tablet'
    | '/terms'
    | '/update-requests'
    | '/wash'
    | '/apply/new'
    | '/apply/thank-you'
    | '/apply/update'
    | '/orders/$orderId'
    | '/settings/branding'
    | '/settings/users'
    | '/styles/$styleId'
    | '/submissions/$submissionId'
    | '/apply'
    | '/apply/status/$referenceCode'
    | '/orders/review/$submissionId'
    | '/submissions/$submissionId/cut-sheet'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/apply-intake'
    | '/boms'
    | '/coming-soon'
    | '/compliance'
    | '/contact'
    | '/cutting'
    | '/dashboard'
    | '/dispatch'
    | '/finance'
    | '/inventory'
    | '/login'
    | '/machines'
    | '/materials'
    | '/orders'
    | '/privacy'
    | '/process'
    | '/qc'
    | '/reports'
    | '/settings'
    | '/sewing'
    | '/shop-floor'
    | '/signup'
    | '/size-ranges'
    | '/sku-mapping'
    | '/styles'
    | '/submissions'
    | '/sustainability'
    | '/tablet'
    | '/terms'
    | '/update-requests'
    | '/wash'
    | '/apply/new'
    | '/apply/thank-you'
    | '/apply/update'
    | '/orders/$orderId'
    | '/settings/branding'
    | '/settings/users'
    | '/styles/$styleId'
    | '/submissions/$submissionId'
    | '/apply/'
    | '/apply/status/$referenceCode'
    | '/orders/review/$submissionId'
    | '/submissions/$submissionId/cut-sheet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  ApplyIntakeRoute: typeof ApplyIntakeRoute
  BomsRoute: typeof BomsRoute
  ComingSoonRoute: typeof ComingSoonRoute
  ComplianceRoute: typeof ComplianceRoute
  ContactRoute: typeof ContactRoute
  CuttingRoute: typeof CuttingRoute
  DashboardRoute: typeof DashboardRoute
  DispatchRoute: typeof DispatchRoute
  FinanceRoute: typeof FinanceRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MachinesRoute: typeof MachinesRoute
  MaterialsRoute: typeof MaterialsRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProcessRoute: typeof ProcessRoute
  QcRoute: typeof QcRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SewingRoute: typeof SewingRoute
  ShopFloorRoute: typeof ShopFloorRoute
  SignupRoute: typeof SignupRoute
  SizeRangesRoute: typeof SizeRangesRoute
  SkuMappingRoute: typeof SkuMappingRoute
  StylesRoute: typeof StylesRouteWithChildren
  SubmissionsRoute: typeof SubmissionsRouteWithChildren
  SustainabilityRoute: typeof SustainabilityRoute
  TabletRoute: typeof TabletRoute
  TermsRoute: typeof TermsRoute
  UpdateRequestsRoute: typeof UpdateRequestsRoute
  WashRoute: typeof WashRoute
  ApplyNewRoute: typeof ApplyNewRoute
  ApplyThankYouRoute: typeof ApplyThankYouRoute
  ApplyUpdateRoute: typeof ApplyUpdateRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
  ApplyStatusReferenceCodeRoute: typeof ApplyStatusReferenceCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wash': {
      id: '/wash'
      path: '/wash'
      fullPath: '/wash'
      preLoaderRoute: typeof WashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-requests': {
      id: '/update-requests'
      path: '/update-requests'
      fullPath: '/update-requests'
      preLoaderRoute: typeof UpdateRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tablet': {
      id: '/tablet'
      path: '/tablet'
      fullPath: '/tablet'
      preLoaderRoute: typeof TabletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles': {
      id: '/styles'
      path: '/styles'
      fullPath: '/styles'
      preLoaderRoute: typeof StylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sku-mapping': {
      id: '/sku-mapping'
      path: '/sku-mapping'
      fullPath: '/sku-mapping'
      preLoaderRoute: typeof SkuMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-ranges': {
      id: '/size-ranges'
      path: '/size-ranges'
      fullPath: '/size-ranges'
      preLoaderRoute: typeof SizeRangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop-floor': {
      id: '/shop-floor'
      path: '/shop-floor'
      fullPath: '/shop-floor'
      preLoaderRoute: typeof ShopFloorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sewing': {
      id: '/sewing'
      path: '/sewing'
      fullPath: '/sewing'
      preLoaderRoute: typeof SewingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc': {
      id: '/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof QcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines': {
      id: '/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof MachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cutting': {
      id: '/cutting'
      path: '/cutting'
      fullPath: '/cutting'
      preLoaderRoute: typeof CuttingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boms': {
      id: '/boms'
      path: '/boms'
      fullPath: '/boms'
      preLoaderRoute: typeof BomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-intake': {
      id: '/apply-intake'
      path: '/apply-intake'
      fullPath: '/apply-intake'
      preLoaderRoute: typeof ApplyIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/': {
      id: '/apply/'
      path: '/apply'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/$submissionId': {
      id: '/submissions/$submissionId'
      path: '/$submissionId'
      fullPath: '/submissions/$submissionId'
      preLoaderRoute: typeof SubmissionsSubmissionIdRouteImport
      parentRoute: typeof SubmissionsRoute
    }
    '/styles/$styleId': {
      id: '/styles/$styleId'
      path: '/$styleId'
      fullPath: '/styles/$styleId'
      preLoaderRoute: typeof StylesStyleIdRouteImport
      parentRoute: typeof StylesRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/branding': {
      id: '/settings/branding'
      path: '/branding'
      fullPath: '/settings/branding'
      preLoaderRoute: typeof SettingsBrandingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/apply/update': {
      id: '/apply/update'
      path: '/apply/update'
      fullPath: '/apply/update'
      preLoaderRoute: typeof ApplyUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/thank-you': {
      id: '/apply/thank-you'
      path: '/apply/thank-you'
      fullPath: '/apply/thank-you'
      preLoaderRoute: typeof ApplyThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/new': {
      id: '/apply/new'
      path: '/apply/new'
      fullPath: '/apply/new'
      preLoaderRoute: typeof ApplyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/$submissionId/cut-sheet': {
      id: '/submissions/$submissionId/cut-sheet'
      path: '/cut-sheet'
      fullPath: '/submissions/$submissionId/cut-sheet'
      preLoaderRoute: typeof SubmissionsSubmissionIdCutSheetRouteImport
      parentRoute: typeof SubmissionsSubmissionIdRoute
    }
    '/orders/review/$submissionId': {
      id: '/orders/review/$submissionId'
      path: '/review/$submissionId'
      fullPath: '/orders/review/$submissionId'
      preLoaderRoute: typeof OrdersReviewSubmissionIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/apply/status/$referenceCode': {
      id: '/apply/status/$referenceCode'
      path: '/apply/status/$referenceCode'
      fullPath: '/apply/status/$referenceCode'
      preLoaderRoute: typeof ApplyStatusReferenceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersReviewSubmissionIdRoute: typeof OrdersReviewSubmissionIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersReviewSubmissionIdRoute: OrdersReviewSubmissionIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface SettingsRouteChildren {
  SettingsBrandingRoute: typeof SettingsBrandingRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBrandingRoute: SettingsBrandingRoute,
  SettingsUsersRoute: SettingsUsersRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface StylesRouteChildren {
  StylesStyleIdRoute: typeof StylesStyleIdRoute
}

const StylesRouteChildren: StylesRouteChildren = {
  StylesStyleIdRoute: StylesStyleIdRoute,
}

const StylesRouteWithChildren =
  StylesRoute._addFileChildren(StylesRouteChildren)

interface SubmissionsSubmissionIdRouteChildren {
  SubmissionsSubmissionIdCutSheetRoute: typeof SubmissionsSubmissionIdCutSheetRoute
}

const SubmissionsSubmissionIdRouteChildren: SubmissionsSubmissionIdRouteChildren =
  {
    SubmissionsSubmissionIdCutSheetRoute: SubmissionsSubmissionIdCutSheetRoute,
  }

const SubmissionsSubmissionIdRouteWithChildren =
  SubmissionsSubmissionIdRoute._addFileChildren(
    SubmissionsSubmissionIdRouteChildren,
  )

interface SubmissionsRouteChildren {
  SubmissionsSubmissionIdRoute: typeof SubmissionsSubmissionIdRouteWithChildren
}

const SubmissionsRouteChildren: SubmissionsRouteChildren = {
  SubmissionsSubmissionIdRoute: SubmissionsSubmissionIdRouteWithChildren,
}

const SubmissionsRouteWithChildren = SubmissionsRoute._addFileChildren(
  SubmissionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  ApplyIntakeRoute: ApplyIntakeRoute,
  BomsRoute: BomsRoute,
  ComingSoonRoute: ComingSoonRoute,
  ComplianceRoute: ComplianceRoute,
  ContactRoute: ContactRoute,
  CuttingRoute: CuttingRoute,
  DashboardRoute: DashboardRoute,
  DispatchRoute: DispatchRoute,
  FinanceRoute: FinanceRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MachinesRoute: MachinesRoute,
  MaterialsRoute: MaterialsRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProcessRoute: ProcessRoute,
  QcRoute: QcRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SewingRoute: SewingRoute,
  ShopFloorRoute: ShopFloorRoute,
  SignupRoute: SignupRoute,
  SizeRangesRoute: SizeRangesRoute,
  SkuMappingRoute: SkuMappingRoute,
  StylesRoute: StylesRouteWithChildren,
  SubmissionsRoute: SubmissionsRouteWithChildren,
  SustainabilityRoute: SustainabilityRoute,
  TabletRoute: TabletRoute,
  TermsRoute: TermsRoute,
  UpdateRequestsRoute: UpdateRequestsRoute,
  WashRoute: WashRoute,
  ApplyNewRoute: ApplyNewRoute,
  ApplyThankYouRoute: ApplyThankYouRoute,
  ApplyUpdateRoute: ApplyUpdateRoute,
  ApplyIndexRoute: ApplyIndexRoute,
  ApplyStatusReferenceCodeRoute: ApplyStatusReferenceCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
